spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: customerModule
        uri: http://CustomerService
        predicates:
        - Path=/customer/**
      - id: bookQueryModule
        uri: lb://BookQueryService
        predicates:
        - Path=/book/**
      - id: bookCommandModule
        uri: http://BookCommandService
        predicates:
          - Path=/book/**
      - id: reviewService
        uri: http://ReviewService
        predicates:
          - Path=/review/**
      - id: borrowingModule
        uri: http://BorrowingService
        predicates:
          - Path=/borrowing/**

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver1:8761/eureka/,
                   http://eurekaserver2:8761/eureka/